### ISSUE TITLE
Error when attempting to make

### ISSUE THREAD

**Issue by sclewis90** [wmandra/aquacomputer_octo-hwmon#1]
I get the error 

"make -C /lib/modules/`uname -r`/build M=$PWD modules
make[1]: Entering directory '/home/ven/aquacomputer_octo-hwmon'
make[1]: *** /lib/modules/6.12.1-arch1-1/build: No such file or directory.  Stop.
make[1]: Leaving directory '/home/ven/aquacomputer_octo-hwmon'
make: *** [Makefile:4: modules] Error 2"

when I attempt to make. How do I resolve this?

**Comment by wmandra** [comment]
do you have kernel headers installed?

**Comment by sclewis90** [comment]
> do you have kernel headers installed?

I did install the headers required, now I get this error https://dpaste.org/VYJzH

**Comment by wmandra** [comment]
seems like it could be a potential arch issue depending on packages installed.

https://bbs.archlinux.org/viewtopic.php?id=284234

i don’t use arch, and have tested that this builds without issue in debian and ubuntu.

**Comment by sclewis90** [comment]
> seems like it could be a potential arch issue depending on packages installed.
> 
> https://bbs.archlinux.org/viewtopic.php?id=284234
> 
> i don’t use arch, and have tested that this builds without issue in debian and ubuntu.
I'm pretty confused on how to approach this to be honest. Do I need a specific kernel version for this driver? Am I supposed to rebuild my kernel and headers?

**Comment by sclewis90** [comment]
I'm pretty confused on how to approach this to be honest. Do I need a specific kernel version for this driver? Am I supposed to rebuild my kernel and headers?

**Comment by wmandra** [comment]
should not require a specific kernel version and no need to build custom kernel. 

i can’t really help with building kernel modules for arch.
